{{ if .Values.metrics.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: $APP_INSTANCE_NAME-metrics-exporter
  labels:
    app.kubernetes.io/name: $APP_INSTANCE_NAME
    app.kubernetes.io/component: influxdb-metrics-exporter
spec:
  containers:
  - name: prometheus-to-sd
    image: gcr.io/google-containers/prometheus-to-sd:v0.3.2
    ports:
    - name: profiler
      containerPort: 6060
    command:
    - /monitor
    - --stackdriver-prefix=custom.googleapis.com
    - --source=$APP_INSTANCE_NAME:http://$APP_INSTANCE_NAME-influxdb-svc:8086/metrics
    - --pod-id=$(POD_NAME)
    - --namespace-id=$(POD_NAMESPACE)
    - --scrape-interval=5s
    - --export-interval=30s
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
{{ end }}
